### ISSUE TITLE
As a developer, I would like all user login information stored in a secure database such as Mlab.

### ISSUE THREAD

**Issue by Lominac** [wjohnson07/fitapp-work#10]

**Comment by wjohnson07** [comment]
mongoDB Atlas account created by @Lominac 
![image](https://user-images.githubusercontent.com/31136807/53903195-12783400-4011-11e9-95ee-eb4575cc5bff.png)

**Comment by wjohnson07** [comment]
@Lominac please close this issue

**Comment by wjohnson07** [comment]
mongoDB Atlas user login information is connected to authentication.

**Comment by Lominac** [comment]
Storing user login credentials in MongoDB Atlas
