### ISSUE TITLE
As a developer, I need the backend code library started in Github.

### ISSUE THREAD

**Issue by wjohnson07** [wjohnson07/fitapp-work#26]

**Comment by ttruongatl** [comment]
http://fitapp-dev-env.us-east-1.elasticbeanstalk.com/graphql
Example:
{
  cat(id: 1){
    id,
    name,
    age
  }
}

**Comment by ttruongatl** [comment]
Done

**Comment by wjohnson07** [comment]
![image](https://user-images.githubusercontent.com/31136807/53902728-d2648180-400f-11e9-9478-d9fbd925f150.png)
