### ISSUE TITLE
As a user, I want to be able to login using Facebook, Twitter and Google.

### ISSUE THREAD

**Issue by wjohnson07** [wjohnson07/fitapp-work#3]

**Comment by Lominac** [comment]
Does Facebook login mean that we can use Instagram (IG) to sign in as well?
Is IG login worth pursuing?

**Comment by wjohnson07** [comment]
Twitter optional.

**Comment by wjohnson07** [comment]
![image](https://user-images.githubusercontent.com/31136807/54131066-fb0dc200-43e7-11e9-8b33-406a9f1cc385.png)

**Comment by wjohnson07** [comment]
![image](https://user-images.githubusercontent.com/31136807/54131094-0660ed80-43e8-11e9-95f0-1cfde7900a5a.png)

**Comment by wjohnson07** [comment]
![image](https://user-images.githubusercontent.com/31136807/54131128-1678cd00-43e8-11e9-84b6-ef301ab2c395.png)

**Comment by wjohnson07** [comment]
All three authentication modes have been confirmed complete for iOS and Android.  This issue can be closed.
