### ISSUE TITLE
As a user I want to be able to login to the app with my phone number.

### ISSUE THREAD

**Issue by Lominac** [wjohnson07/fitapp-work#4]

**Comment by ttruongatl** [comment]
![login](https://user-images.githubusercontent.com/5000972/53341803-85c7ca80-38da-11e9-84e4-11d3ac6214d1.png)
![verification code](https://user-images.githubusercontent.com/5000972/53341804-85c7ca80-38da-11e9-9dfd-c267746cda83.png)
![verification code copy](https://user-images.githubusercontent.com/5000972/53341805-85c7ca80-38da-11e9-9b15-f540f740ad8a.png)

Update Login UI mockup with phone number

**Comment by wjohnson07** [comment]
![image](https://user-images.githubusercontent.com/31136807/54133439-7a04f980-43ec-11e9-9f73-43960d069ac2.png)

**Comment by wjohnson07** [comment]
@Lominac please review and close this issue.

**Comment by Lominac** [comment]
iOS TestFlight and Google Play Test successful with 4 digit SMS authentication
