### ISSUE TITLE
As a user, I'd like to land on a homepage once logged into the application.

### ISSUE THREAD

**Issue by Lominac** [wjohnson07/fitapp-work#7]
The homepage should allow the user to access:
     1) User Profile 
     2) Workout Generator
     3) Macro Calculators

**Comment by wjohnson07** [comment]
![image](https://user-images.githubusercontent.com/31136807/54131426-b3d40100-43e8-11e9-89b4-4b48b414773a.png)

**Comment by wjohnson07** [comment]
@Lominac please confirm and close this issue.

**Comment by Lominac** [comment]
- User Profile Modal / Navigation Tab    - milestone 3
- Workout Generator Navigation Tab     - milestone 4
- Macro Calculator Navigation Tab        - milestone 5
