### ISSUE TITLE
As a User, I would like a confirmation, or error message, so I know if my login credentials are correct.

### ISSUE THREAD

**Issue by Lominac** [wjohnson07/fitapp-work#8]
The error message would tell the user if their password or username is incorrect when they are trying to login.

**Comment by wjohnson07** [comment]
@Lominac is this issue still needed?

**Comment by Lominac** [comment]
This would be for creating an account through our app. Do we want to have that feature available or only allow access through sms and social media?

**Comment by Lominac** [comment]
Social Media Login - Social media login has their own error messages when entering user credentials 

Phone SMS - When the phone number is input with the incorrect number of digits, an error message will let the user know that the phone number is incorrect
